config/routes.rb
Battleleague::Application.routes.draw do
  resources :comments

  resources :alliances

  resources :armies do
    get 'edit_form_alliance'
    patch 'update_form_alliance'
    get 'edit_move'
    put 'move'
  end
  put 'move/:id' => 'armies#move' # this is needed for the complicated move form on the game show page

  resources :spaces

  resources :maps

  resources :games do
    get 'set_turns'
    get 'resolve_battle'
  end

  devise_for :users

  root 'games#index'

end

app/models/map.rb
class Map < ActiveRecord::Base
  has_one :game
  has_many :spaces
  belongs_to :user

  def self.for_selection
    maps = []
    Map.all.each do |map|
      maps << map if not map.game
    end
    maps
  end

  def width
    self.spaces.maximum("x_cord")
  end

  def height
    self.spaces.maximum("y_cord")
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    @is_edit = false
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
    @is_edit = true
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    width = params[:width].to_i
    height = params[:height].to_i

    if width > 20 or height > 20
      format.html { render action: 'new' }
    end

    @map.save
    @map.spaces.create({x_cord: width, y_cord: height, terrain: "", victory_points: 0})

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render action: 'show', status: :created, location: @map }
      else
        format.html { render action: 'new' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(
        :name,
        :description,
        :user_id
      )
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.haml
= simple_form_for @map do |f|
  - if @map.errors.any?
    #error_explanation
      %h2= "#{pluralize(@map.errors.count, "error")} prohibited this map from being saved:"
      %ul
        - @map.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-md-6
      = f.input :name, input_html: { class: "string form-control" }
  .row
    .col-md-6
      = f.input :description, input_html: { class: "string form-control" }

  .row
    .col-md-3
      %label Width:
      %input{ name: "width", class: "string form-control" }
    .col-md-3
      %label Height:
      %input{ name: "height", class: "string form-control" }
  
  = f.hidden_field :user_id, value: current_user.id

  %br
  .actions
    = f.submit 'Save', class: "btn btn-primary"

app/views/maps/_map.html.haml
.map-container{ style: "width: 95%" }
  - map.height.times do |y|
    - map.width.times do |x|
      - space = map.spaces.where(x_cord: x+1, y_cord: y+1).first
      - if not space
        - space = Space.new(x_cord: x+1, y_cord: y+1, terrain: "", victory_points: 0, map: map)
        - temp_space = true
      - w = (100/map.width) * 0.95
      - g = (100/map.width) * 0.05
      %span.space{id: "#{space.x_cord}-#{space.y_cord}", style: "background-color: #{color_of_space(space, current_user)};width: #{w}%; height: #{w}%; position: absolute; top: #{(w + g) * (space.y_cord-1)}%; left: #{(w + g) * (space.x_cord-1)}%;"} 
        = hidden_field_tag "is_clicked", 0
        - had_info = false
        - if space.terrain and space.terrain != ""
          = space.terrain
          - had_info = true
        - if space.victory_points and space.victory_points > 0
          %span.glyphicon.glyphicon-star-empty.pull-right
          %span.pull-right= space.victory_points
          - had_info = true
        - if had_info
          %br
        - if map.game and current_user
          - armies = space.armies
          - if map.game.has_battle_at(x+1, y+1) and not map.game.has_unresolved_armies_at(x+1, y+1)
            = link_to "Resolve Battle", game_resolve_battle_path(map.game)
          - armies.each do |army|
            - if army.user == current_user or army.close_to(current_user) or army.allied_to(current_user)
              - if army.user == current_user and army == army.game.current_army and not army.game.needs_resolved
                %span.my-army= army.name
                = hidden_field_tag "army_id_" + army.id.to_s, army.id
                = hidden_field_tag "movement_rate_" + army.id.to_s, army.movement_rate
                %span.move Move
                %br
              - elsif army.user == current_user and army.needs_resolved
                %span.my-army= army.name
                = hidden_field_tag "army_id_" + army.id.to_s, army.id
                = hidden_field_tag "movement_rate_" + army.id.to_s, army.movement_rate
                - if army.is_winner
                  %span.move.battle-resolve-winner Victory!
                - else
                  %span.move.battle-resolve-loser Defeat!
                %br
              - elsif army.user == current_user
                %span.my-army= army.name
                %br
              - elsif army.allied_to(current_user)
                %span.allied-army= army.name + " (" + army.user.name + ")"
                %br
              - else
                %span.enemy-army= army.name + " (" + army.user.name + ")"
                %br
        - if is_edit
          - if temp_space
            = form_tag new_space_path, :method => 'get' do
              = hidden_field_tag :x_cord, x+1
              = hidden_field_tag :y_cord, y+1
              = hidden_field_tag :map_id, map.id
              %span= submit_tag "Add", :name => nil, class: "space-edit"
          - else
            = form_tag edit_space_path(space), :method => 'get' do
              = hidden_field_tag :x_cord, x+1
              = hidden_field_tag :y_cord, y+1
              = hidden_field_tag :map_id, map.id
              %span= submit_tag "Edit", :name => nil, class: "space-edit"

app/views/maps/edit.html.haml
.container
  .row
    .col-md-2
      .row
        %h1 Editing map
      .row
        .btn-group
          = link_to 'Show', @map, class: "btn btn-default"
          = link_to 'Back', maps_path, class: "btn btn-default"
    .col-md-8
      = render partial: "map", locals: { map: @map, is_edit: @is_edit }
%br
%br

app/views/maps/index.html.haml
%h1 Listing maps

%table.table.table-hover.table-responsive
  %tr
    %th Name
    %th Width
    %th Height
    %th Creator
    %th
    %th

  - @maps.each do |map|
    - if not map.game
      %tr
        %td= link_to map.name, map
        %td= map.width
        %td= map.height
        %td= map.user ? map.user.name : "Unknown"
        - if map.user == current_user
          %td= link_to 'Edit', edit_map_path(map)
          %td= link_to 'Delete', map, :method => :delete, :data => { :confirm => 'Are you sure?' }
        - else
          %td
          %td

%br

= link_to 'New Map', new_map_path, class: "btn btn-primary"

app/views/maps/new.html.haml
%h1 New map

= render 'form'

%br
= link_to 'Back', maps_path, class: "btn btn-default"

app/views/maps/show.html.haml
.container
  .row
    .col-md-2
      .row
        %h2= @map.name
      .row
        %p
          = @map.description
          %br
          - if @map.game
            The game that this map is apart of is
            = link_to @map.game.name, @map.game
      .row
        .btn-group
          = link_to 'Back', maps_path, class: "btn btn-default"
          = link_to 'Edit', edit_map_path(@map), class: "btn btn-default"
    .col-md-8
      = render partial: "map", locals: { map: @map, is_edit: @is_edit }
%br
%br