config/routes.rb
Battleleague::Application.routes.draw do
  resources :comments

  resources :alliances

  resources :armies do
    get 'edit_form_alliance'
    patch 'update_form_alliance'
    get 'edit_move'
    put 'move'
  end
  put 'move/:id' => 'armies#move' # this is needed for the complicated move form on the game show page

  resources :spaces

  resources :maps

  resources :games do
    get 'set_turns'
    get 'resolve_battle'
  end

  devise_for :users

  root 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :map, :dependent => :destroy
  has_and_belongs_to_many :users
  has_many :armies, dependent: :destroy
  belongs_to :game_master, :class_name => 'User', :foreign_key => 'game_master_id'
  has_many :alliances, dependent: :destroy
  has_many :comments, through: :armies
  accepts_nested_attributes_for :armies

  def battling_armies
    (1..self.map.width).each do |x|
      (1..self.map.height).each do |y|
        space = self.map.spaces.where(x_cord: x, y_cord: y).first
        space = Space.new(x_cord: x, y_cord: y, terrain: "", victory_points: 0, map: map) if not space
        space.armies.each do |army1|
          space.armies.each do |army2|
            if not army1.allied_to(army2.user)
              return space.armies
            end
          end
        end
      end
    end
    return []
  end

  def has_unresolved_armies_at x, y
    return false if not self.has_battle_at x, y
    space = self.map.spaces.where(x_cord: x, y_cord: y).first
    space = Space.new(x_cord: x, y_cord: y, terrain: "", victory_points: 0, map: map) if not space
    space.armies.each do |army|
      return true if army.is_winner or army.is_loser
    end
    return false
  end

  def has_battle_at x, y
    space = self.map.spaces.where(x_cord: x, y_cord: y).first
    space = Space.new(x_cord: x, y_cord: y, terrain: "", victory_points: 0, map: map) if not space
    space.armies.each do |army1|
      space.armies.each do |army2|
        return true if (not army1.allied_to(army2.user)) and (army1 != army2)
      end
    end
    return false
  end

  def needs_resolved
    return true if self.armies.where(is_winner: true).size > 0
    return true if self.armies.where(is_loser: true).size > 0
    (1..self.map.width).each do |x|
      (1..self.map.height).each do |y|
        space = self.map.spaces.where(x_cord: x, y_cord: y).first
        space = Space.new(x_cord: x, y_cord: y, terrain: "", victory_points: 0, map: map) if not space
        space.armies.each do |army1|
          space.armies.each do |army2|
            if not army1.allied_to(army2.user) and army1 != army2
              return true
            end
          end
        end
      end
    end
    return false
  end

  def current_army
    turn = self.armies.maximum("turn_count")
    self.armies.where(turn_count: turn).first
  end

  def players
    users = self.users
    users = users.uniq
    users
  end

  def has_joined user
    if self.armies.where(user: user).first
      true
    else
      false
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def set_turns
    @game = Game.find(params[:game_id])
    if current_user != @game.game_master
      redirect_to @game, notice: "Only the game master can do that!"
      return
    end
    @game.armies.each_with_index do |army, i|
      army.turn_count = i + 1
      army.save
    end
    redirect_to @game
  end

  # GET /games
  # GET /games.json
  def index
    if not current_user
      redirect_to new_user_session_path 
      return
    end
    #@games = current_user.games
    # HACK WARNING!!!
    #@games.each do |game|
    #  @games = @games - [game] if @games.include? game
    #  @games << game
    #end
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @comment = Comment.new
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    @game.save

    old_map = Map.find(params[:game][:map_id]) 
    @game.map = old_map.dup
    old_map.spaces.each do |old_space|
      new_space = old_space.dup
      @game.map.spaces << new_space
    end
    @game.map.save

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    @game.battling_armies.each do |army|
      army.is_loser = true if army.is_winner == false
      army.save
    end
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  def resolve_battle
    @game = Game.find(params[:game_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(
        :name,
        :rule_set,
        :description,
        :objective,
        :details,
        :game_master_id,
        armies_attributes: [
          :id,
          :is_winner,
          :is_loser
        ]
      )
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.haml
= simple_form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      %h2= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-3
      = f.input :name, input_html: { class: "string form-control" }
    .col-md-3
      = f.input :rule_set, input_html: { class: "string form-control" }
    .col-md-3
      = f.association :map, collection: Map.for_selection, input_html: { class: "dropdown form-control" }
  .row
    .col-md-9
      = f.input :description, input_html: { class: "string form-control" }
  .row
    .col-md-9
      = f.input :objective, input_html: { class: "string form-control" }
  .row
    .col-md-9
      = f.input :details, input_html: { class: "string form-control" }

  = f.hidden_field :game_master_id, value: current_user.id

  %br
  .actions
    = f.submit 'Save', class: "btn btn-primary"

app/views/games/edit.html.haml
%h1 Editing game

= render 'form'

%br
.btn-group
  = link_to 'Show', @game, class: "btn btn-link"
  = link_to 'Back', games_path, class: "btn btn-link"

app/views/games/index.html.haml
%h1 Listing games

%table.table.table-hover.table-responsive
  %tr
    %th Name
    %th Rule Set
    %th Map Name
    %th Game Master
    %th
    %td
    %td

  - @games.each do |game|
    %tr
      %td= link_to game.name, game
      %td= game.rule_set
      %td= game.map.name
      - if game.game_master == current_user
        %td  You
        - if current_user.games.include? game
          %td
        - else
          %td= link_to "Join Game", new_army_path(game_id: game.id), class: "", notice: "Create an army to join the game"
        %td= link_to 'Edit', edit_game_path(game)
        %td= link_to 'Delete', game, :method => :delete, :data => { :confirm => 'Are you sure?' }
      - else
        %td= game.game_master.name
        - if current_user.games.include? game
          %td
        - else
          %td= link_to "Join Game", new_army_path(game_id: game.id), class: "", notice: "Create an army to join the game"
        %td
        %td

%br

= link_to 'New Game', new_game_path, class: "btn btn-primary"

app/views/games/new.html.haml
%h1 New game

= render 'form'

%br
= link_to 'Back', games_path, class: "btn btn-default"

app/views/games/resolve_battle.html.haml
= simple_form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      %h2= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg

  %h2 Who Won?
  = f.fields_for :armies do |army|
    - if @game.battling_armies.include? army.object
      = army.input :is_winner, as: :boolean, label: army.object.name, input_html: { class: "is_winner" }
      = army.hidden_field :id, value: army.object.id
  %br

  %br
  .actions
    = f.submit 'Save', class: "btn btn-primary"

app/views/games/show.html.haml
.row
  .col-md-4
    .row
      - flash.each do |name, msg|
        - if msg.is_a?(String)
          %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
            %a.close{"data-dismiss" => "alert"} &times;
            = content_tag :div, msg, :id => "flash_#{name}"
    .row
      %br
      .btn-group.pull-left
        - if current_user.games.include? @game
          = link_to "New Army", new_army_path(game_id: @game.id), class: "btn btn-default"
        - else
          = link_to "Join Game", new_army_path(game_id: @game.id), class: "btn btn-default", notice: "Create an army to join the game"
        = link_to "New Alliance", new_alliance_path(game_id: @game.id), class: "btn btn-default"
    %br
    .row
      %table.table.table-hover.table-responsive
        %tr
          %th Name
          %th
          %th Player
          %th Turn Count
          %th Alliance
        - @game.armies.order('turn_count DESC').each do |army|
          %tr
            - if army.user == current_user
              %td= link_to army.name, army
              - if ( army == @game.current_army and army.turn_count != 0 and (army.x_cord and army.y_cord) ) or army.needs_resolved
                %td 
                  = simple_form_for army, url: army_move_path(army), method: :put do |f|
                    = f.hidden_field :x_cord, value: army.x_cord
                    = f.hidden_field :y_cord, value: army.y_cord
                    = f.submit "Skip Move", class: "skip"
              - elsif not (army.x_cord and army.y_cord)
                %td= link_to "Place Army", army_edit_move_path(army)
              - else
                %td
              %td  You
              - if army == @game.current_army and not army.turn_count == 0
                %td.my-next-turn 
                  = army.turn_count
                  &nbsp;(Next Move)
              - elsif army.turn_count == 0
                %td= link_to "Needs Placed", army_edit_move_path(army)
              - else
                %td= army.turn_count
              - if army.alliance
                %td
                  = army.alliance.name
                  = link_to "Leave", army_update_form_alliance_path(army, alliance_id: 0), method: :patch
              - else
                %td
                  Not Allied -
                  = link_to "Ally", army_edit_form_alliance_path(army)
            - else
              %td= army.name
              %td
              %td= army.user.name
              - if army == @game.current_army and army.turn_count != 0
                %td.enemy-next-turn 
                  = army.turn_count
                  &nbsp;(Next Move)
              - elsif army.turn_count == 0
                %td Not Placed
              - else
                %td= army.turn_count
              - if army.alliance
                %td= army.alliance.name
              - else
                %td No Alliance
    .row
      .comment-section
        %table.table.table-hover.table-responsive.table-condensed.table-striped
          - @game.comments.each do |c|
            - if c.is_viewable_by(current_user)
              %tr
                %span.comment
                  %td.col-md-5
                    - if c.army.user == current_user and c.comment_type != "whisper"
                      You said
                    - elsif c.comment_type != "whisper"
                      = c.army.user.name + " says"
                    - if c.comment_type == "public"
                      (public)
                    - elsif c.comment_type == "team"
                      = "(Message to " + c.army.alliance.name + ")"
                    - elsif c.comment_type == "whisper"
                      - if c.army.user == current_user
                        - if c.user == current_user
                          = "You whispered to yourself:"
                        - else
                          = "You whispered to " + c.user.name
                      - else
                        = c.army.user.name + " whispered to you:"
                  %td
                    = c.content
    .row
      - if @game.has_joined(current_user)
        = simple_form_for @comment do |f|
          .row
            .col-md-12
              = f.input :content, label: "Comment", input_html: { class: "string form-control" }
          .row
            .col-md-5
              = f.input :comment_type, label: "Type", collection: comment_types(@game, current_user), selected: "Public", input_html: { class: "dropdown form-control" }
            .col-md-4{ id: "whisper" }
              = f.association :user, label: "Whisper To", collection: @game.players, input_html: { class: "dropdown form-control" }
            = f.hidden_field :army_id, value: @game.armies.where(user: current_user).first.id
            .col-md-3
              %br
              = f.submit "Create", class: "btn btn-primary shift-down pull-right"
      - else 
        You must 
        = link_to "join", new_army_path(game_id: @game.id)
        the game to comment
  .col-md-8
    .row
      .col-md-12
        = render partial: "maps/map", locals: { map: @game.map, is_edit: false }
    .row
      .col-md-12
        %p.left-margin * Remember that you might not be close enough to see some enemy armies!
%br
%br
.row
  .col-md-4
    %h2= @game.name
    %p
      %b Description:
      %br
      =  @game.description
      %br
      %br
    %p
      %b Objective:
      %br
      =  @game.objective
      %br
      %br
    %p
      %b Other Details:
      %br
      =  @game.details
  .col-md-8
    %table.table.table-hover.table-responsive
      %tr
        %th Name
        %th
        %th Player
        %th Army Type
        %th Point Cost
        %th Turn Count
        %th Alliance
      - @game.armies.order('turn_count DESC').each do |army|
        %tr
          - if army.user == current_user
            %td= link_to army.name, army
            - if army == @game.current_army and army.turn_count != 0 and (army.x_cord and army.y_cord)
              %td 
                = simple_form_for army, url: army_move_path(army), method: :put do |f|
                  = f.hidden_field :x_cord, value: army.x_cord
                  = f.hidden_field :y_cord, value: army.y_cord
                  = f.submit "Skip Move", class: "skip"
            - elsif not (army.x_cord and army.y_cord)
              %td= link_to "Place Army", army_edit_move_path(army)
            - else
              %td
            %td  You
            %td= army.army_type
            %td= army.point_cost
            - if army == @game.current_army and not army.turn_count == 0
              %td.my-next-turn 
                = army.turn_count
                &nbsp;(Next Move)
            - elsif army.turn_count == 0
              %td= link_to "Needs Placed", army_edit_move_path(army)
            - else
              %td= army.turn_count
            - if army.alliance
              %td
                = army.alliance.name
                = link_to "Leave", army_update_form_alliance_path(army, alliance_id: 0), method: :patch
            - else
              %td
                Not Allied -
                = link_to "Ally", army_edit_form_alliance_path(army)
          - else
            %td= army.name
            %td
            %td= army.user.name
            %td= army.army_type
            %td= army.point_cost
            - if army == @game.current_army and army.turn_count != 0
              %td.enemy-next-turn 
                = army.turn_count
                &nbsp;(Next Move)
            - elsif army.turn_count == 0
              %td Not Placed
            - else
              %td= army.turn_count
            - if army.alliance
              %td= army.alliance.name
            - else
              %td No Alliance
%br
.btn-group
  = link_to 'Back', games_path, class: "btn btn-default"
  - if @game.game_master == current_user
    = link_to 'Edit', edit_game_path(@game), class: "btn btn-default"
    = link_to 'Reset Turn Count', game_set_turns_path(@game), class: "btn btn-default"
%br
%br
%br
%br
.hidden
  .move-icon
    = form_tag :action => 'move', :controller => 'armies', :method => :put do |f|
      = hidden_field_tag "army[x_cord]"
      = hidden_field_tag "army[y_cord]"
      = hidden_field_tag "_method", "put"
      = submit_tag "", :style => "display:none"