config/routes.rb
Battleleague::Application.routes.draw do
  resources :comments

  resources :alliances

  resources :armies do
    get 'edit_form_alliance'
    patch 'update_form_alliance'
    get 'edit_move'
    put 'move'
  end
  put 'move/:id' => 'armies#move' # this is needed for the complicated move form on the game show page

  resources :spaces

  resources :maps

  resources :games do
    get 'set_turns'
    get 'resolve_battle'
  end

  devise_for :users

  root 'games#index'

end

app/models/army.rb
class Army < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  belongs_to :alliance
  has_many   :comments, :dependent => :destroy
  validates  :movement_rate, presence: true
  validates  :game_id, presence: true
  validates  :name, presence: true
  validate :cordinates_with_limits

  def needs_resolved
    if self.is_winner or self.is_loser
      true 
    else
      false
    end
  end

  def allied_to user
    armies = []
    user.armies.where(game: self.game).each do |army|
      if self.alliance and army.alliance == self.alliance 
        return true
      end
    end
    return false
  end

  def cordinates_with_limits
    if x_cord and y_cord
      if x_cord > game.map.width or x_cord < 1
        errors.add(:x_cord, "Coordinates not in the bounds of the map")
      elsif y_cord > game.map.height or y_cord < 1
        errors.add(:y_cord, "Coordinates not in the bounds of the map")
      end
    end
  end

  def move_check x, y
    if self.x_cord and self.y_cord
      x = x.to_i
      y = y.to_i
      if x - self.x_cord > self.movement_rate or x - self.x_cord < -1 * self.movement_rate
        return false
      elsif y - self.y_cord > self.movement_rate or y - self.y_cord < -1 * self.movement_rate
        return false
      end
    end
    return true
  end

  def close_to user
    user.armies.where(game: self.game).each do |army|
      if army.x_cord and army.y_cord
        if (army.x_cord - self.x_cord < 2 and army.x_cord - self.x_cord > -2) and (army.y_cord - self.y_cord < 2 and army.y_cord - self.y_cord > -2)
          return true
        end
      end
    end
    return false
  end

end

app/controllers/armies_controller.rb
class ArmiesController < ApplicationController
  before_action :set_army, only: [:show, :edit, :update, :destroy]

  # GET /armies
  # GET /armies.json
  def index
    @armies = Army.all.where(user: current_user)
  end

  # GET /armies/1
  # GET /armies/1.json
  def show
  end

  # GET /armies/new
  def new
    @army = Army.new
  end

  # GET /armies/1/edit
  def edit
    redirect_to @army.game, notice: 'That is not your army' if not current_user.armies.include? @army
  end

  # POST /armies
  # POST /armies.json
  def create
    @army = Army.new(army_params)

    @army.user.games << @army.game

    @army.turn_count = 0

    #@army.game.armies.each do |army|
    #  army.turn_count += 1 if army.turn_count != 0
    #  army.save
    #end

    respond_to do |format|
      if @army.save
        format.html { redirect_to @army.game, notice: 'Army was successfully created.' }
        format.json { render action: 'show', status: :created, location: @army }
      else
        format.html { render action: 'new' }
        format.json { render json: @army.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit_form_alliance
    @army = Army.find(params[:army_id])
  end

  def update_form_alliance
    @army = Army.find(params[:army_id])
    if params[:alliance_id] == "0"
      @army.user.armies.where(game_id: @army.game.id).each do |army|
        army.alliance = nil
        army.save
      end
      redirect_to @army.game, notice: @army.name + " is now apart of the " + @army.alliance.name + " alliance"
      return
    end

    alliance_id = params[:army][:alliance_id]
    if alliance_id 
      @army.alliance = Alliance.find(alliance_id)
      @army.save
      @army.user.armies.where(game_id: @army.game.id).each do |army|
        army.alliance = @army.alliance
        army.save
      end
      redirect_to @army.game, notice: @army.name + " is now apart of the " + @army.alliance.name + " alliance"
      return
    end
  end

  def edit_move
    @army = Army.find(params[:army_id])
    redirect_to @army.game, notice: 'That is not your army' if not current_user.armies.include? @army
  end

  def move
    id = params[:id] ? params[:id] : params[:army_id]
    @army = Army.find(id)
    
    if params[:x_cord] and params[:y_cord]
      if (not @army.move_check(params[:army][:x_cord], params[:army][:y_cord])) or (@army.needs_resolved)
        redirect_to edit_army_path(@army), notice: "This army can only move " + @army.movement_rate.to_s + " and is currently at (" + @army.x_cord.to_s + "," + @army.y_cord.to_s + ")"
        return
      elsif (@army != @army.game.current_army) and (@army.x_cord and @army.y_cord)
        redirect_to edit_army_path(@army), notice: "It is not this armies turn, it will be in " + (@army.game.current_army.turn_count - @army.turn_count).to_s + " turns"
        return
      end
    end

    if not @army.is_loser and not @army.is_winner
      @army.turn_count = 0
      @army.save
      @army.game.armies.each do |army|
        army.turn_count += 1 if army.turn_count
        army.save
      end
    end

    @army.is_loser = false
    @army.is_winner = false

    respond_to do |format|
      space = @army.game.map.spaces.where(x_cord: @army.x_cord, y_cord: @army.y_cord).first
      space = @army.game.map.spaces.create(x_cord: @army.x_cord, y_cord: @army.y_cord, army: @army) if not space
      if @army.update(army_params)
        space.army = @army
        space.save
        if @army.game
          format.html { redirect_to @army.game, notice: 'Army was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { redirect_to @army, notice: 'Army was successfully updated.' }
          format.json { head :no_content }
        end
      else
        format.html { render action: 'edit' }
        format.json { render json: @army.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /armies/1
  # PATCH/PUT /armies/1.json
  def update
    respond_to do |format|
      if @army.update(army_params)
        if @army.game
          format.html { redirect_to @army.game, notice: 'Army was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { redirect_to @army, notice: 'Army was successfully updated.' }
          format.json { head :no_content }
        end
      else
        format.html { render action: 'edit' }
        format.json { render json: @army.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /armies/1
  # DELETE /armies/1.json
  def destroy
    @army.destroy
    respond_to do |format|
      format.html { redirect_to armies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_army
      @army = Army.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def army_params
      params.require(:army).permit(
        :name,
        :description,
        :army_type,
        :point_cost,
        :movement_rate,
        :x_cord,
        :y_cord,
        :game_id,
        :user_id,
        :alliance_id
      )
    end
end

app/helpers/armies_helper.rb
module ArmiesHelper
  def alliances_available_to army
    alliances = []
    army.game.alliances.each do |alliance|
      alliances << alliance if alliance.users.include? army.user
    end
    alliances
  end
end

app/views/armies/_form.html.haml
= simple_form_for @army do |f|
  - if @army.errors.any?
    #error_explanation
      %h2= "#{pluralize(@army.errors.count, "error")} prohibited this army from being saved:"
      %ul
        - @army.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-md-8
      = f.input :name, input_html: { class: "string form-control" }
  .row
    .col-md-8
      = f.input :description, input_html: { class: "string form-control" }
  .row
    .col-md-2
      - if params[:game_id]
        = f.input :game, input_html: { readonly: true, value: Game.find(params[:game_id]).name, class: "dropdown form-control" }
        = f.hidden_field :game_id, value: params[:game_id]
      - else
        = f.association :game, input_html: { class: "dropdown form-control" }
    .col-md-2
      = f.input :army_type, input_html: { class: "string form-control" }
    .col-md-2
      = f.input :point_cost, input_html: { class: "string form-control" }
    .col-md-2
      = f.input :movement_rate, input_html: { class: "string form-control" }

  = f.hidden_field :user_id, value: current_user.id

  %br
  .actions
    = f.submit 'Save', class: "btn btn-primary"

app/views/armies/edit.html.haml
%h1 Editing army
= simple_form_for @army do |f|
  - if @army.errors.any?
    #error_explanation
      %h2= "#{pluralize(@army.errors.count, "error")} prohibited this army from being saved:"
      %ul
        - @army.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-2
      = f.input :x_cord, input_html: { class: "string form-control" }
    .col-md-2
      = f.input :y_cord, input_html: { class: "string form-control" }
    .col-md-2
      = f.association :alliance, collection: @army.game.alliances, input_html: { class: "dropdown form-control" }
  %br
  .actions
    = f.submit 'Save', class: "btn btn-primary"
%br
.btn-group
  = link_to 'Show', @army, class: "btn btn-default"
  = link_to 'Back', game_path(@army.game), class: "btn btn-default"

app/views/armies/edit_form_alliance.html.haml
%h1 Editing army
= simple_form_for @army, url: army_update_form_alliance_path(@army) do |f|
  - if @army.errors.any?
    #error_explanation
      %h2= "#{pluralize(@army.errors.count, "error")} prohibited this army from being saved:"
      %ul
        - @army.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-2
      = f.association :alliance, collection: alliances_available_to(@army), input_html: { class: "dropdown form-control" }
  %br
  .actions
    = f.submit 'Save', class: "btn btn-primary"
%br
.btn-group
  = link_to 'Show', @army, class: "btn btn-default"
  = link_to 'Back', game_path(@army.game), class: "btn btn-default"

app/views/armies/edit_move.html.haml
%h1 Editing army
= simple_form_for @army, url: army_move_path(@army), method: :put do |f|
  - if @army.errors.any?
    #error_explanation
      %h2= "#{pluralize(@army.errors.count, "error")} prohibited this army from being saved:"
      %ul
        - @army.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-2
      = f.input :x_cord, input_html: { class: "string form-control" }
    .col-md-2
      = f.input :y_cord, input_html: { class: "string form-control" }
  %br
  .actions
    = f.submit 'Save', class: "btn btn-primary"
%br
.btn-group
  = link_to 'Show', @army, class: "btn btn-default"
  = link_to 'Back', game_path(@army.game), class: "btn btn-default"

app/views/armies/index.html.haml
%h1 Listing armies

%table.table.table-hover.table-responsive
  %tr
    %th Name
    %th Army Type
    %th Point Cost
    %th Game
    %th
    %th

  - @armies.each do |army|
    %tr
      %td= link_to army.name, army
      %td= army.army_type
      %td= army.point_cost
      %td= link_to army.game.name, army.game
      %td= link_to "Edit", edit_army_path(army)
      %td= link_to "Delete", army, method: :delete

%br

= link_to 'New Army', new_army_path, class: "btn btn-primary"

app/views/armies/new.html.haml
- if params[:game_id]
  %h1 
    New army for 
    = Game.find(params[:game_id]).name
- else
  %h1 New army
= render 'form'

%br
- if params[:game_id]
  = link_to 'Back', game_path(params[:game_id]), class: "btn btn-default"
- else
  = link_to 'Back', armies_path, class: "btn btn-default"

app/views/armies/show.html.haml
.text-center
  %h2= @army.name
  %p= @army.description
  %p
    This army is fighting in 
    = link_to @army.game.name, @army.game

.btn-group
  = link_to 'Edit', edit_army_path(@army), class: "btn btn-link", class: "btn btn-default"
  = link_to 'Back', armies_path, class: "btn btn-link", class: "btn btn-default"
%br
%br