config/routes.rb
Battleleague::Application.routes.draw do
  resources :comments

  resources :alliances

  resources :armies do
    get 'edit_form_alliance'
    patch 'update_form_alliance'
    get 'edit_move'
    put 'move'
  end
  put 'move/:id' => 'armies#move' # this is needed for the complicated move form on the game show page

  resources :spaces

  resources :maps

  resources :games do
    get 'set_turns'
    get 'resolve_battle'
  end

  devise_for :users

  root 'games#index'

end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
%head
  %title Battleleague
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  - if current_user and current_user.theme
    = stylesheet_link_tag    current_user.theme,       media: "all", "data-turbolinks-track" => true
  - else
    = stylesheet_link_tag    "theme.min",       media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
%head
  %body
    - if current_user
      %nav.navbar.navbar-default{role: "navigation"}
        .container-fluid
          .navbar-header
            = link_to "Battle League", games_path, class: "navbar-brand"
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li
                = link_to "Play", games_path
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                  My Domain
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to "Games", games_path
                  %li
                    = link_to "Armies", armies_path
                  %li
                    = link_to "Maps", maps_path
                  %li
                    = link_to "Alliances", alliances_path
                  -# TODO
                    %li
                      %a{href: "#"} Opponents
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                  Create
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to "Game", new_game_path
                  %li
                    = link_to "Army", new_army_path
                  %li
                    = link_to "Map", new_map_path
                  %li
                    = link_to "Alliance", new_alliance_path
            -#
              %form.navbar-form.navbar-left{role: "search"}
                .form-group
                  %input.form-control{placeholder: "Search", type: "text"}/
                %button.btn.btn-default{type: "submit"} Submit
            %ul.nav.navbar-nav.navbar-right
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                  = current_user.name
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to "Account Info", edit_user_registration_path
                  %li
                    = link_to "Change Password", edit_user_registration_path
                  %li.divider
                  %li
                    = link_to "Logout", destroy_user_session_path, method: :delete
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
    - else
      %nav.navbar.navbar-default{role: "navigation"}
        .container-fluid
          .navbar-header
            = link_to "Battle League", new_user_session_path, class: "navbar-brand"
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to "Create Account", new_user_registration_path
              %li
                = link_to "Login", new_user_session_path
    .container
      - if not ( params[:controller] == "games" and params[:action] == "show" )
        - flash.each do |name, msg|
          - if msg.is_a?(String)
            %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
              %a.close{"data-dismiss" => "alert"} &times;
              = content_tag :div, msg, :id => "flash_#{name}"
      = yield
  %body
%html